nodeLinker: node-modules

plugins:
    - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
      spec: '@yarnpkg/plugin-version'

unsafeHttpWhitelist:
    - localhost

yarnPath: .yarn/releases/yarn-3.6.0.cjs
