nodeLinker: node-modules

npmRegistryServer: 'http://127.0.0.1:4873'

plugins:
    - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
      spec: '@yarnpkg/plugin-version'

unsafeHttpWhitelist:
    - 127.0.0.1

yarnPath: .yarn/releases/yarn-3.6.0.cjs
