/**
 * ICure Medical Device Micro Service
 * ICure Medical Device Micro Service
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AddressDto, Annotation, IAnnotation, mapTo } from '@icure/typescript-common'
import { ITelecom, Telecom } from './Telecom.model'

/**
 * the list of addresses (with address type).
 */
@mapTo(AddressDto)
export class Address {
    addressType?: AddressAddressTypeEnum
    description?: string
    street?: string
    houseNumber?: string
    postboxNumber?: string
    postalCode?: string
    city?: string
    state?: string
    country?: string
    note?: string
    telecoms: Telecom[] = []
    notes: Annotation[] = []
    encryptedSelf?: string

    toJSON(): IAddress {
        return {
        addressType: this.addressType,
        description: this.description,
        street: this.street,
        houseNumber: this.houseNumber,
        postboxNumber: this.postboxNumber,
        postalCode: this.postalCode,
        city: this.city,
        state: this.state,
        country: this.country,
        note: this.note,
        telecoms: this.telecoms.map(item => item.toJSON()),
        notes: this.notes.map(item => item.toJSON()),
        encryptedSelf: this.encryptedSelf,
        }
    }

    constructor(json: Partial<IAddress>) {
        if (json["addressType"] !== undefined) {
            this.addressType = json["addressType"]!
        }
        if (json["description"] !== undefined) {
            this.description = json["description"]!
        }
        if (json["street"] !== undefined) {
            this.street = json["street"]!
        }
        if (json["houseNumber"] !== undefined) {
            this.houseNumber = json["houseNumber"]!
        }
        if (json["postboxNumber"] !== undefined) {
            this.postboxNumber = json["postboxNumber"]!
        }
        if (json["postalCode"] !== undefined) {
            this.postalCode = json["postalCode"]!
        }
        if (json["city"] !== undefined) {
            this.city = json["city"]!
        }
        if (json["state"] !== undefined) {
            this.state = json["state"]!
        }
        if (json["country"] !== undefined) {
            this.country = json["country"]!
        }
        if (json["note"] !== undefined) {
            this.note = json["note"]!
        }
        if (json["telecoms"] !== undefined) {
            this.telecoms = json["telecoms"]!.map((item: any) => new Telecom(item))
        }
        if (json["notes"] !== undefined) {
            this.notes = json["notes"]!.map((item: any) => new Annotation(item))
        }
        if (json["encryptedSelf"] !== undefined) {
            this.encryptedSelf = json["encryptedSelf"]!
        }
    }
}

export interface IAddress {
    addressType?: AddressAddressTypeEnum
    description?: string
    street?: string
    houseNumber?: string
    postboxNumber?: string
    postalCode?: string
    city?: string
    state?: string
    country?: string
    note?: string
    notes: IAnnotation[]
    telecoms: ITelecom[]
    encryptedSelf?: string
}

export type AddressAddressTypeEnum = 'home' | 'work' | 'vacation' | 'hospital' | 'clinic' | 'hq' | 'other' | 'temporary' | 'postal' | 'diplomatic' | 'reference'
