/**
 * ICure Medical Device Micro Service
 * ICure Medical Device Micro Service
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { base64string, CodingReference, EntityId, forceUuid, HealthcarePartyDto, ICodingReference, IProperty, ISystemMetaDataOwner, mapTo, Property, SystemMetaDataOwner } from '@icure/typescript-common'
import { Address, IAddress } from './Address.model'
import { IPersonName, PersonName } from './PersonName.model'

@mapTo(HealthcarePartyDto)
export class HealthcareProfessional {
    /**
     * the Id of the healthcare party. We encourage using either a v4 UUID or a HL7 Id.
     */
    id: EntityId
    /**
     * the revision of the healthcare party in the database, used for conflict management / optimistic locking.
     */
    rev?: string
    /**
     * creation timestamp of the object.
     */
    created?: number
    /**
     * last modification timestamp of the object.
     */
    modified?: number
    /**
     * A label is an item from a codification system that qualifies a doctor as being member of a certain class, whatever the value it might have taken. If the label qualifies the content of a field, it means that whatever the content of the field, the label will always apply. LOINC is a codification system typically used for labels.
     * Example: HealthcareProfessional is an organisation
     */
    labels: CodingReference[] = []
    /**
     * A code is an item from a codification system that qualifies the content of this doctor.
     * Example: doctors specialty
     */
    codes: CodingReference[] = []
    /**
     * the soft delete timestamp. When a user is ”deleted“, this is set to a non null value: the moment of the deletion
     */
    deletionDate?: number
    /**
     * The full name of the healthcare party, used mainly when the healthcare party is an organization
     */
    name?: string
    /**
     * the lastname (surname) of the healthcare party. This is the official lastname that should be used for official administrative purposes.
     */
    lastName?: string
    /**
     * the firstname (name) of the healthcare party.
     */
    firstName?: string
    /**
     * the list of all names of the healthcare party, also containing the official full name information. Ordered by preference of use. First element is therefore the official name used for the healthcare party in the application
     */
    names: PersonName[] = []
    /**
     * the gender of the healthcare party: male, female, indeterminate, changed, changedToMale, changedToFemale, unknown
     */
    gender?: HealthcareProfessionalGenderEnum
    /**
     * Mr., Ms., Pr., Dr. ...
     */
    civility?: string
    /**
     * Medical specialty of the healthcare party
     */
    speciality?: string
    /**
     * Id of parent of the user representing the healthcare party.
     */
    parentId?: string
    /**
     * The list of addresses (with address type).
     */
    addresses: Address[] = []
    /**
     * The list of languages spoken by the patient ordered by fluency (alpha-2 code http://www.loc.gov/standards/iso639-2/ascii_8bits.html).
     */
    languages: string[] = []
    /**
     * A picture usually saved in JPEG format.
     */
    picture?: base64string
    /**
     * Medical specialty of the healthcare party codified using FHIR or Kmehr codificaiton scheme
     */
    specialityCodes: CodingReference[] = []
    /**
     * Text notes.
     */
    notes?: string
    properties: Property[] = []
    systemMetaData?: SystemMetaDataOwner

    toJSON(): IHealthcareProfessional {
        return {
            id: this.id,
            rev: this.rev,
            created: this.created,
            modified: this.modified,
            labels: this.labels.map((item) => item.toJSON()),
            codes: this.codes.map((item) => item.toJSON()),
            deletionDate: this.deletionDate,
            name: this.name,
            lastName: this.lastName,
            firstName: this.firstName,
            names: this.names.map((item) => item.toJSON()),
            gender: this.gender,
            civility: this.civility,
            speciality: this.speciality,
            parentId: this.parentId,
            addresses: this.addresses.map((item) => item.toJSON()),
            languages: this.languages.map((item) => item),
            picture: this.picture,
            specialityCodes: this.specialityCodes.map((item) => item.toJSON()),
            notes: this.notes,
            properties: this.properties.map((item) => item.toJSON()),
            systemMetaData: !!this.systemMetaData ? this.systemMetaData.toJSON() : undefined,
        }
    }

    constructor(json: Partial<IHealthcareProfessional>) {
        this.id = forceUuid(json['id']!)
        if (json['rev'] !== undefined) {
            this.rev = json['rev']!
        }
        if (json['created'] !== undefined) {
            this.created = json['created']!
        }
        if (json['modified'] !== undefined) {
            this.modified = json['modified']!
        }
        if (json['labels'] !== undefined) {
            this.labels = json['labels']!.map((item: any) => new CodingReference(item))
        }
        if (json['codes'] !== undefined) {
            this.codes = json['codes']!.map((item: any) => new CodingReference(item))
        }
        if (json['deletionDate'] !== undefined) {
            this.deletionDate = json['deletionDate']!
        }
        if (json['name'] !== undefined) {
            this.name = json['name']!
        }
        if (json['lastName'] !== undefined) {
            this.lastName = json['lastName']!
        }
        if (json['firstName'] !== undefined) {
            this.firstName = json['firstName']!
        }
        if (json['names'] !== undefined) {
            this.names = json['names']!.map((item: any) => new PersonName(item))
        }
        if (json['gender'] !== undefined) {
            this.gender = json['gender']!
        }
        if (json['civility'] !== undefined) {
            this.civility = json['civility']!
        }
        if (json['speciality'] !== undefined) {
            this.speciality = json['speciality']!
        }
        if (json['parentId'] !== undefined) {
            this.parentId = json['parentId']!
        }
        if (json['addresses'] !== undefined) {
            this.addresses = json['addresses']!.map((item: any) => new Address(item))
        }
        if (json['languages'] !== undefined) {
            this.languages = json['languages']!.map((item: any) => item)
        }
        if (json['picture'] !== undefined) {
            this.picture = json['picture']!
        }
        if (json['specialityCodes'] !== undefined) {
            this.specialityCodes = json['specialityCodes']!.map((item: any) => new CodingReference(item))
        }
        if (json['notes'] !== undefined) {
            this.notes = json['notes']!
        }
        if (json['properties'] !== undefined) {
            this.properties = json['properties']!.map((item: any) => new Property(item))
        }
        if (json['systemMetaData'] !== undefined) {
            this.systemMetaData = new SystemMetaDataOwner(json['systemMetaData']!)
        }
    }
}

export interface IHealthcareProfessional {
    id?: EntityId
    rev?: string
    created?: number
    modified?: number
    labels: ICodingReference[]
    codes: ICodingReference[]
    deletionDate?: number
    name?: string
    lastName?: string
    firstName?: string
    names: IPersonName[]
    gender?: HealthcareProfessionalGenderEnum
    civility?: string
    speciality?: string
    parentId?: string
    addresses: IAddress[]
    languages: string[]
    picture?: base64string
    specialityCodes: ICodingReference[]
    notes?: string
    properties: IProperty[]
    systemMetaData?: ISystemMetaDataOwner
}

export type HealthcareProfessionalGenderEnum = 'male' | 'female' | 'indeterminate' | 'changed' | 'changedToMale' | 'changedToFemale' | 'unknown'
