/**
 * ICure Medical Device Micro Service
 * ICure Medical Device Micro Service
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapTo, PatientHealthCarePartyDto } from '@icure/typescript-common'

/**
 * Links (usually for therapeutic reasons) between this patient and healthcare parties (of class PatientHealthcareParty).
 */
@mapTo(PatientHealthCarePartyDto)
export class PatientHealthCareParty {
    type: PatientHealthCarePartyTypeEnum = 'other'
    healthcarePartyId?: string

    toJSON(): IPatientHealthCareParty {
        return {
        type: this.type,
        healthcarePartyId: this.healthcarePartyId,
        }
    }

    constructor(json: Partial<IPatientHealthCareParty>) {
        if (json["type"] !== undefined) {
            this.type = json["type"]!
        }
        if (json["healthcarePartyId"] !== undefined) {
            this.healthcarePartyId = json["healthcarePartyId"]!
        }
    }
}

export interface IPatientHealthCareParty {
    type: PatientHealthCarePartyTypeEnum
    healthcarePartyId?: string
}

export type PatientHealthCarePartyTypeEnum = 'doctor' | 'referral' | 'medicalhouse' | 'retirementhome' | 'hospital' | 'other' | 'referringphysician' | 'managingorganization'
