/**
 * ICure Medical Device Micro Service
 * ICure Medical Device Micro Service
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapTo, PatientHealthCarePartyDto } from '@icure/typescript-common'

/**
 * Links (usually for therapeutic reasons) between this patient and healthcare parties (of class PatientHealthcareParty).
 */
@mapTo(PatientHealthCarePartyDto)
export class PatientHealthCareParty {
    constructor(json: Partial<IPatientHealthCareParty>) {
        Object.assign(this as PatientHealthCareParty, json as IPatientHealthCareParty)
    }

    'type': PatientHealthCarePartyTypeEnum
    'healthcarePartyId'?: string

    static toJSON(instance: PatientHealthCareParty): IPatientHealthCareParty {
        const pojo: IPatientHealthCareParty = {} as IPatientHealthCareParty
        pojo['type'] = instance.type
        if (instance.healthcarePartyId !== undefined) pojo['healthcarePartyId'] = instance.healthcarePartyId
        return pojo
    }

    static fromJSON(pojo: IPatientHealthCareParty): PatientHealthCareParty {
        const obj = {} as IPatientHealthCareParty
        obj['type'] = pojo['type']
        if (pojo['healthcarePartyId'] !== undefined) {
            obj['healthcarePartyId'] = pojo['healthcarePartyId']!
        }
        return new PatientHealthCareParty(obj)
    }
}

export interface IPatientHealthCareParty {
    type: PatientHealthCarePartyTypeEnum
    healthcarePartyId?: string
}

export type PatientHealthCarePartyTypeEnum = 'doctor' | 'referral' | 'medicalhouse' | 'retirementhome' | 'hospital' | 'other' | 'referringphysician' | 'managingorganization'
