/**
 * ICure Medical Device Micro Service
 * ICure Medical Device Micro Service
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapTo, TelecomDto } from '@icure/typescript-common'

@mapTo(TelecomDto)
export class Telecom {
    telecomType?: TelecomTelecomTypeEnum
    telecomNumber?: string
    telecomDescription?: string

    toJSON(): ITelecom {
        return {
        telecomType: this.telecomType,
        telecomNumber: this.telecomNumber,
        telecomDescription: this.telecomDescription,
        }
    }

    constructor(json: Partial<ITelecom> ) {
        if (json["telecomType"] !== undefined) {
            this.telecomType = json["telecomType"]!
        }
        if (json["telecomNumber"] !== undefined) {
            this.telecomNumber = json["telecomNumber"]!
        }
        if (json["telecomDescription"] !== undefined) {
            this.telecomDescription = json["telecomDescription"]!
        }
    }
}

export interface ITelecom {
    telecomType?: TelecomTelecomTypeEnum
    telecomNumber?: string
    telecomDescription?: string
}

export type TelecomTelecomTypeEnum = 'mobile' | 'phone' | 'email' | 'fax' | 'skype' | 'im' | 'medibridge' | 'ehealthbox' | 'apicrypt' | 'web' | 'print' | 'disk' | 'other' | 'pager'
