/**
 * ICure Medical Device Micro Service
 * ICure Medical Device Micro Service
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Telecom as TelecomDto } from '@icure/api'
import { mapTo } from '@icure/typescript-common'

@mapTo(TelecomDto)
export class Telecom {
  constructor(json: ITelecom) {
    Object.assign(this as Telecom, json as ITelecom)
  }

  'telecomType'?: TelecomTelecomTypeEnum
  'telecomNumber'?: string
  'telecomDescription'?: string

  static toJSON(instance: Telecom): any {
    const pojo: any = {}
    pojo['telecomType'] = instance.telecomType
    pojo['telecomNumber'] = instance.telecomNumber
    pojo['telecomDescription'] = instance.telecomDescription
    return pojo
  }

  static fromJSON(pojo: any): Telecom {
    return new Telecom({ telecomType: pojo['telecomType'], telecomNumber: pojo['telecomNumber'], telecomDescription: pojo['telecomDescription'] })
  }
}

interface ITelecom {
  telecomType?: TelecomTelecomTypeEnum
  telecomNumber?: string
  telecomDescription?: string
}

export type TelecomTelecomTypeEnum =
  | 'mobile'
  | 'phone'
  | 'email'
  | 'fax'
  | 'skype'
  | 'im'
  | 'medibridge'
  | 'ehealthbox'
  | 'apicrypt'
  | 'web'
  | 'print'
  | 'disk'
  | 'other'
  | 'pager'
