/**
 * ICure Medical Device Micro Service
 * ICure Medical Device Micro Service
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AuthenticationTokenDto } from '../index'
import { mapTo } from '../utils/decorators'

/**
 * Encrypted and time-limited Authentication tokens used for inter-applications authentication
 */
@mapTo(AuthenticationTokenDto)
export class AuthenticationToken {
    /**
     * Encrypted token
     */
    token: string
    /**
     * Validity starting time of the token
     */
    creationTime: number
    /**
     * Token validity in seconds
     */
    validity: number

    toJSON(): IAuthenticationToken {
        return {
            token: this.token,
            creationTime: this.creationTime,
            validity: this.validity,
        }
    }

    constructor(json: Partial<IAuthenticationToken> & { token: string; creationTime: number; validity: number }) {
        this.token = json['token']!
        this.creationTime = json['creationTime']!
        this.validity = json['validity']!
    }
}

export interface IAuthenticationToken {
    token: string
    creationTime: number
    validity: number
}
