/**
 * ICure Medical Device Micro Service
 * ICure Medical Device Micro Service
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Codified list of professions exercised by this patient.
 */
export class CodingReference {
  constructor(json: ICodingReference) {
    Object.assign(this as CodingReference, json);
  }

  "id"?: string;
  "type"?: string;
  "code"?: string;
  "version"?: string;

    static toJSON(instance: CodingReference): any {
        const pojo: any = {}
        pojo["id"] = instance.id
        pojo["type"] = instance.type
        pojo["code"] = instance.code
        pojo["version"] = instance.version
        return pojo
    }

    static fromJSON(pojo: any): CodingReference {
        return new CodingReference({id: pojo["id"], type: pojo["type"], code: pojo["code"], version: pojo["version"]})
    }
}

interface ICodingReference {
  id?: string;
  type?: string;
  code?: string;
  version?: string;
}
