/**
 * ICure Medical Device Micro Service
 * ICure Medical Device Micro Service
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CodeStub, ISO639_1 } from "@icure/api";
import { mapTo } from "../utils/decorators";

/**
 * Codified list of professions exercised by this patient.
 */
@mapTo(CodeStub)
export class CodingReference {
    constructor(json: ICodingReference) {
        Object.assign(this as CodingReference, json);
    }

    "id"?: string;
    "type"?: string;
    "code"?: string;
    "version"?: string;
    "label"?: Map<ISO639_1, string>;

    static toJSON(instance: CodingReference): any {
        const pojo: any = {}
        pojo["id"] = instance.id
        pojo["type"] = instance.type
        pojo["code"] = instance.code
        pojo["version"] = instance.version
        pojo["label"] = !!instance.label ? Object.fromEntries([...instance.label.entries()].map(([k, v]) => [k, v])) : undefined
        return pojo
    }

    static fromJSON(pojo: any): CodingReference {
        return new CodingReference({id: pojo["id"], type: pojo["type"], code: pojo["code"], version: pojo["version"], label: pojo["label"] ? new Map(Object.entries(pojo["label"]).map(([k, v]: [any, any]) => [k, v])) : undefined})
    }
}

interface ICodingReference {
    id?: string;
    type?: string;
    code?: string;
    version?: string;
    label?: Map<ISO639_1, string>;
}
