/**
 * ICure Medical Device Micro Service
 * ICure Medical Device Micro Service
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class Delegation {
  constructor(json: IDelegation) {
    Object.assign(this as Delegation, json);
  }

  "tags": Array<string>;
  "owner"?: string;
  "delegatedTo"?: string;
  "key"?: string;

    static toJSON(instance: Delegation): any {
        const pojo: any = {}
        pojo["tags"] = instance.tags.map(item => item)
        pojo["owner"] = instance.owner
        pojo["delegatedTo"] = instance.delegatedTo
        pojo["key"] = instance.key
        return pojo
    }

    static fromJSON(pojo: any): Delegation {
        return new Delegation({tags: pojo["tags"].map((item: any) => item), owner: pojo["owner"], delegatedTo: pojo["delegatedTo"], key: pojo["key"]})
    }
}

interface IDelegation {
  tags?: Array<string>;
  owner?: string;
  delegatedTo?: string;
  key?: string;
}
