/**
 * ICure Medical Device Micro Service
 * ICure Medical Device Micro Service
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class Filter {
    description?: string

    toJSON(): IFilter {
        return {
            description: this.description,
        }
    }

    constructor(json: Partial<IFilter>) {
        if (json['description'] !== undefined) {
            this.description = json['description']!
        }
    }
}

export interface IFilter {
    description?: string
}
