/**
 * ICure Medical Device Micro Service
 * ICure Medical Device Micro Service
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class Filter {
    constructor(json: Partial<IFilter>) {
        Object.assign(this as Filter, json)
    }

    'description': string

    static toJSON(instance: Filter): IFilter {
        const pojo: IFilter = {} as IFilter
        pojo['description'] = instance.description
        return pojo
    }

    static fromJSON(pojo: IFilter): Filter {
        const obj = {} as IFilter
        obj['description'] = pojo['description']
        return new Filter(obj)
    }
}

interface IFilter {
    description?: string
}
