/**
 * ICure Medical Device Micro Service
 * ICure Medical Device Micro Service
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class Filter {
  constructor(json: IFilter) {
    Object.assign(this as Filter, json);
  }

  "description": string;

    static toJSON(instance: Filter): any {
        const pojo: any = {}
        pojo["description"] = instance.description
        return pojo
    }

    static fromJSON(pojo: any): Filter {
        return new Filter({description: pojo["description"]})
    }
}

interface IFilter {
  description?: string;
}
