/**
 * ICure Medical Device Micro Service
 * ICure Medical Device Micro Service
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class InlineResponse403 {
    '_short'?: number
    '_char'?: string
    '_int'?: number
    '_long'?: number
    '_float'?: number
    '_double'?: number
    'direct'?: boolean
    'readOnly'?: boolean

    toJSON(): IInlineResponse403 {
        return {
            _short: this._short,
            _char: this._char,
            _int: this._int,
            _long: this._long,
            _float: this._float,
            _double: this._double,
            direct: this.direct,
            readOnly: this.readOnly,
        }
    }

    constructor(json: Partial<IInlineResponse403>) {
        if (json['_short'] !== undefined) {
            this._short = json['_short']!
        }
        if (json['_char'] !== undefined) {
            this._char = json['_char']!
        }
        if (json['_int'] !== undefined) {
            this._int = json['_int']!
        }
        if (json['_long'] !== undefined) {
            this._long = json['_long']!
        }
        if (json['_float'] !== undefined) {
            this._float = json['_float']!
        }
        if (json['_double'] !== undefined) {
            this._double = json['_double']!
        }
        if (json['direct'] !== undefined) {
            this.direct = json['direct']!
        }
        if (json['readOnly'] !== undefined) {
            this.readOnly = json['readOnly']!
        }
    }
}

export interface IInlineResponse403 {
    _short?: number
    _char?: string
    _int?: number
    _long?: number
    _float?: number
    _double?: number
    direct?: boolean
    readOnly?: boolean
}
