/**
 * ICure Medical Device Micro Service
 * ICure Medical Device Micro Service
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class InlineResponse403 {
  constructor(json: IInlineResponse403) {
    Object.assign(this as InlineResponse403, json);
  }

  "_short"?: number;
  "_char"?: string;
  "_int"?: number;
  "_long"?: number;
  "_float"?: number;
  "_double"?: number;
  "direct"?: boolean;
  "readOnly"?: boolean;

    static toJSON(instance: InlineResponse403): any {
        const pojo: any = {}
        pojo["_short"] = instance._short
        pojo["_char"] = instance._char
        pojo["_int"] = instance._int
        pojo["_long"] = instance._long
        pojo["_float"] = instance._float
        pojo["_double"] = instance._double
        pojo["direct"] = instance.direct
        pojo["readOnly"] = instance.readOnly
        return pojo
    }

    static fromJSON(pojo: any): InlineResponse403 {
        return new InlineResponse403({_short: pojo["_short"], _char: pojo["_char"], _int: pojo["_int"], _long: pojo["_long"], _float: pojo["_float"], _double: pojo["_double"], direct: pojo["direct"], readOnly: pojo["readOnly"]})
    }
}

interface IInlineResponse403 {
  _short?: number;
  _char?: string;
  _int?: number;
  _long?: number;
  _float?: number;
  _double?: number;
  direct?: boolean;
  readOnly?: boolean;
}
