/**
 * ICure Medical Device Micro Service
 * ICure Medical Device Micro Service
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Delegation } from "./Delegation";

export class SystemMetaDataEncrypted {
  constructor(json: ISystemMetaDataEncrypted) {
    Object.assign(this as SystemMetaDataEncrypted, json);
  }

  "secretForeignKeys": Array<string>;
  "cryptedForeignKeys": Map<string, Set<Delegation>>;
  "delegations": Map<string, Set<Delegation>>;
  "encryptionKeys": Map<string, Set<Delegation>>;
  "encryptedSelf"?: string;

    static toJSON(instance: SystemMetaDataEncrypted): any {
        const pojo: any = {}
        pojo["secretForeignKeys"] = instance.secretForeignKeys.map(item => item)
        pojo["cryptedForeignKeys"] = Object.fromEntries([...instance.cryptedForeignKeys.entries()].map(([k, v]) => [k, Array.from([...v].map(item => Delegation.toJSON(item)))]))
        pojo["delegations"] = Object.fromEntries([...instance.delegations.entries()].map(([k, v]) => [k, Array.from([...v].map(item => Delegation.toJSON(item)))]))
        pojo["encryptionKeys"] = Object.fromEntries([...instance.encryptionKeys.entries()].map(([k, v]) => [k, Array.from([...v].map(item => Delegation.toJSON(item)))]))
        pojo["encryptedSelf"] = instance.encryptedSelf
        return pojo
    }

    static fromJSON(pojo: any): SystemMetaDataEncrypted {
        return new SystemMetaDataEncrypted({secretForeignKeys: pojo["secretForeignKeys"].map((item: any) => item), cryptedForeignKeys: new Map(Object.entries(pojo["cryptedForeignKeys"]).map(([k, v]: [any, any]) => [k, new Set(v.map((item: any) => Delegation.fromJSON(item)))])), delegations: new Map(Object.entries(pojo["delegations"]).map(([k, v]: [any, any]) => [k, new Set(v.map((item: any) => Delegation.fromJSON(item)))])), encryptionKeys: new Map(Object.entries(pojo["encryptionKeys"]).map(([k, v]: [any, any]) => [k, new Set(v.map((item: any) => Delegation.fromJSON(item)))])), encryptedSelf: pojo["encryptedSelf"]})
    }
}

interface ISystemMetaDataEncrypted {
  secretForeignKeys?: Array<string>;
  cryptedForeignKeys?: Map<string, Set<Delegation>>;
  delegations?: Map<string, Set<Delegation>>;
  encryptionKeys?: Map<string, Set<Delegation>>;
  encryptedSelf?: string;
}
