export enum ContactPointTelecomTypeEnum {
    MOBILE = 'mobile',
    PHONE = 'phone',
    EMAIL = 'email',
    FAX = 'fax',
    SKYPE = 'skype',
    IM = 'im',
    MEDIBRIDGE = 'medibridge',
    EHEALTHBOX = 'ehealthbox',
    APICRYPT = 'apicrypt',
    WEB = 'web',
    PRINT = 'print',
    DISK = 'disk',
    OTHER = 'other',
    PAGER = 'pager',
}
